In [0]:
import pandas as pd
import numpy as np
import matplotlib as plt


In [10]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = ['sepal-lenghth', 'sepal-width', 'petal-length', 'petal-width', 'class']
df = pd.read_csv(url, names = names)
df.head()

sepal-lenghth  sepal-width  petal-length  petal-width        class
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa

In [0]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

array = df.values

x = array[:, 0:4]
y = array[:, 4]

validation_size = 20
seed = 7

x_train, x_validation, y_train, y_validation = train_test_split(x,y,test_size = validation_size, random_state = seed)

In [19]:
scaler = preprocessing.StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)

x_validation = scaler.transform(x_validation)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [23]:
from sklearn.svm import SVC

model = SVC()

model.fit(x_train,y_train)




SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
prediction = model.predict(x_validation)

In [26]:
from sklearn.metrics import  confusion_matrix, accuracy_score, classification_report
print(accuracy_score(y_validation,prediction))

0.85


In [29]:
print(classification_report(y_validation,prediction))


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.86      0.75      0.80         8
 Iris-virginica       0.67      0.80      0.73         5

      micro avg       0.85      0.85      0.85        20
      macro avg       0.84      0.85      0.84        20
   weighted avg       0.86      0.85      0.85        20



In [28]:
print(confusion_matrix(y_validation,prediction))

[[7 0 0]
 [0 6 2]
 [0 1 4]]
