In [0]:
import pandas as pd
import numpy as np
import matplotlib as plt


In [5]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
names = ['sepal-lenghth', 'sepal-width', 'petal-length', 'petal-width', 'class']
df = pd.read_csv(url, names = names)
df.head()

sepal-lenghth  sepal-width  petal-length  petal-width        class
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa

In [0]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

array = df.values

x = array[:, 0:4]
y = array[:, 4]

validation_size = 20
seed = 7

x_train, x_validation, y_train, y_validation = train_test_split(x,y,test_size = validation_size, random_state = seed)

In [0]:
scaler = preprocessing.StandardScaler().fit(x_train)
x_train = scaler.transform(x_train)

x_validation = scaler.transform(x_validation)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [0]:
from sklearn.svm import SVC

model = SVC()

model.fit(x_train,y_train)




SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
prediction = model.predict(x_validation)

In [0]:
from sklearn.metrics import  confusion_matrix, accuracy_score, classification_report
print(accuracy_score(y_validation,prediction))

0.85


In [0]:
print(classification_report(y_validation,prediction))


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.86      0.75      0.80         8
 Iris-virginica       0.67      0.80      0.73         5

      micro avg       0.85      0.85      0.85        20
      macro avg       0.84      0.85      0.84        20
   weighted avg       0.86      0.85      0.85        20



In [0]:
print(confusion_matrix(y_validation,prediction))

[[7 0 0]
 [0 6 2]
 [0 1 4]]


In [7]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(x_train,y_train)


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [0]:
prediction = model.predict(x_validation)

In [9]:
from sklearn.metrics import  confusion_matrix, accuracy_score, classification_report
print(accuracy_score(y_validation,prediction))

0.75


In [10]:
print(classification_report(y_validation,prediction))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       1.00      0.38      0.55         8
 Iris-virginica       0.50      1.00      0.67         5

      micro avg       0.75      0.75      0.75        20
      macro avg       0.83      0.79      0.74        20
   weighted avg       0.88      0.75      0.73        20



In [11]:
print(confusion_matrix(y_validation,prediction))

[[7 0 0]
 [0 3 5]
 [0 0 5]]
